
CREATE TABLE IF NOT EXISTS fingerpost_wire_entry (
    id BIGSERIAL PRIMARY KEY,
    external_id TEXT,
    ingested_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    content JSONB NOT NULL
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;

