version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
    ports:
      - '4566:4566'
    volumes:
      - '/tmp/localstack:/var/lib/localstack'
      - ./localstack:/etc/localstack/init/ready.d
  db:
    image: postgres:14
    container_name: newswires-db
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=newswires

