#!/usr/bin/env bash

set -e

red='\x1B[0;31m'
plain='\x1B[0m' # No Color

isInstalled() {
  hash "$1" 2>/dev/null
}

checkRequirement() {
  if ! isInstalled "$1"; then
    echo -e "${red}[MISSING DEPENDENCY] $1 not found. Please install $1${plain}"
    exit 1
  fi
}

checkRequirements() {
  # server side
  checkRequirement java
  checkRequirement sbt

  # client side
  checkRequirement npm

  # used for postgres and AWS localstack
  checkRequirement docker

  # other
  checkRequirement nginx
  checkRequirement aws
  checkRequirement scala-cli
}

checkForJavaHome() {
  echo "Checking JAVA_HOME"
  if [[ -z "$JAVA_HOME" ]]; then
    echo "  JAVA_HOME not set, please set it before continuing"
    echo "  This can be done by adding \"export JAVA_HOME=\$(/usr/libexec/java_home)\" to ~/.profile"
    exit 1
  else
    echo "  JAVA_HOME is set to $JAVA_HOME"
  fi
}

checkNodeVersion() {
  runningNodeVersion=$(node -v)
  requiredNodeVersion=$(cat "$ROOT_DIR/.nvmrc")

  if [ "$runningNodeVersion" != "$requiredNodeVersion" ]; then
    echo -e "${red}Using wrong version of Node. Required ${requiredNodeVersion}. Running ${runningNodeVersion}.${plain}"
    exit 1
  fi
}

echo "Checking for required software..."
checkForJavaHome
checkRequirements
checkNodeVersion
echo "All expected software is installed"