#!/usr/bin/env bash

set -e

green='\x1B[0;32m'
red='\x1B[0;31m'
plain='\x1B[0m' # No Color

AWS_PROFILE='editorial-feeds'
AWS_REGION='eu-west-1'
STACK='editorial-feeds'
POSTGRES_PORT='5432'
APP_NAME='newswires'
TUNNEL_GREP_PATTERN="AWS-StartPortForwardingSessionToRemoteHost.*localPortNumber.*$POSTGRES_PORT"
EXISTING_TUNNELS=$(pgrep -f "$TUNNEL_GREP_PATTERN" || true)

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=${DIR}/..


# copied over from the Grid. Not 100% sure of the rationale, but perhaps: https://stackoverflow.com/questions/56520354/getting-an-amazonkinesisexception-status-code-502-when-using-localstack-from-ja
export AWS_CBOR_DISABLE=true

for arg in "$@"; do
  if [ "$arg" == "--debug" ]; then
    IS_DEBUG=true
    shift
  fi
  if [ "$arg" == "--use-CODE" ]; then
    USE_CODE=true
    shift
  fi
done


hasCredentials() {
  STATUS=$(aws sts get-caller-identity --profile ${AWS_PROFILE} 2>&1 || true)
  if [[ ${STATUS} =~ (ExpiredToken) ]]; then
    echo -e "${red}Credentials for the ${AWS_PROFILE} profile are expired. Please fetch new credentials and run this again.${plain}"
    exit 1
  elif [[ ${STATUS} =~ ("could not be found") ]]; then
    echo -e "${red}Credentials for the ${AWS_PROFILE} profile are missing. Please ensure you have the right credentials.${plain}"
    exit 1
  fi
}


tunnelToAwsDb() {
    if (docker stats --no-stream &> /dev/null); then
      docker compose down
    fi
    if [[ -n $EXISTING_TUNNELS ]]; then
      echo "RE-USING EXISTING TUNNEL TO CODE POSTGRES (on port ${POSTGRES_PORT})"
    else
      "$DIR/rds-tunnel.sh" \
        --app "$APP_NAME" \
        --stack "$STACK" \
        --stage CODE \
        --region "$AWS_REGION" \
        --profile "$AWS_PROFILE" \
        --local-port "$POSTGRES_PORT" \
        --background
      echo "TUNNEL ESTABLISHED TO CODE POSTGRES (on port ${POSTGRES_PORT})"
    fi
}

startDockerContainers() {
  if [[ $EXISTING_TUNNELS ]]; then
    echo "KILLING EXISTING TUNNEL TO CODE POSTGRES (on port ${POSTGRES_PORT})"
    pkill -f "$TUNNEL_GREP_PATTERN"
  fi
  docker compose up -d --wait
  echo "Applying database migrations if necessary..."

  yes | ./db/flyway.sc migrate local
}

startIngestionLambda() {
  pushd "$ROOT_DIR/ingestion-lambda"
  npm install
  npm run dev
  popd
}

establishDBConnection() {
  if [ "$USE_CODE" == "true" ]; then
    echo "Using CODE DB. Starting tunnel to AWS DB."
    tunnelToAwsDb
  else
    echo "Using the local stack. Starting Docker."
    startDockerContainers
  fi

  if ! lsof -i :${POSTGRES_PORT} >/dev/null; then
      echo -e "${red}No database connection available on port ${POSTGRES_PORT} - something's gone wrong! ${plain}"
      exit 1
  fi
}

startPlayApp() {
  # pushd to find build.sbt and allow this script to be executed from any location (but ideally from the project root)
  echo "========================================================="
  echo "= Press cmd-C then cmd-D to stop"
  echo "========================================================="
  pushd "$ROOT_DIR/${APP_NAME}"
  if [ "$IS_DEBUG" == true ] ; then
    sbt -jvm-debug 5005 run
  else
    sbt run
  fi
  popd
}

main() {
    hasCredentials
    source "$ROOT_DIR/scripts/check-requirements"
    establishDBConnection

    if [ "$USE_CODE" == "true" ]; then
      echo "Using CODE. Starting Play App."
      USE_CODE_DB=true startPlayApp
    else
      echo "Using the local environment. Starting Ingestion Lambda and Play App."
      # run all three, and terminate together when the user presses `ctrl+c`: https://stackoverflow.com/a/52033580
      (trap 'kill 0' SIGINT; startIngestionLambda & startPlayApp & wait)
    fi
}

main
