#!/usr/bin/env bash

npm run build -w reingestion-lambda

zip -FSjr "reingestion-lambda/dist/reingestion-lambda.zip" "reingestion-lambda/dist/handler.js"

aws lambda update-function-code \
    --function-name editorial-feeds-CODE-news-ReingestionLambdaCODEDDF-zwIlC2J8xojr \
    --profile editorial-feeds \
    --region eu-west-1 \
    --zip-file "fileb://reingestion-lambda/dist/reingestion-lambda.zip"