name: build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-latest-migration:
    name: Check the latest migration version
    if: github.ref == 'refs/pull/483/merg'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.SSM_AUTH }}

      - name: Checkout branch
        uses: actions/checkout@v5
      
      - name: Check the latest migration version
        run: 
          ./scripts/check-latest-migration.sh
  build:
    needs: check-latest-migration
    if: needs.check-latest-migration.result == 'success' || needs.check-latest-migration.result == 'skipped'
    name: Build and upload to riffraff
    runs-on: ubuntu-22.04
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.SSM_AUTH }}

      - name: Check the latest migration version
        if: github.ref == 'refs/pull/483/merge'
        run: 
          ./scripts/check-latest-migration.sh      

      - name: Setup node for CDK
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
          node-version-file: '.nvmrc'

      - name: Set up Scala CLI
        uses: VirtusLab/scala-cli-setup@v1.5

      - name: Set up test environment
        run: ./scripts/setup-test-env.sh    
      
      # See https://github.com/guardian/setup-scala
      - name: Setup Java and sbt
        uses: guardian/setup-scala@v1

      - name: Lint and test
        run: |
          npm ci
          npm run lint:ci
          npm run typecheck
          npm test

      - name: Build CDK
        working-directory: cdk
        run: |
          npm run synth

      - name: Build ingestion-lambda
        working-directory: ingestion-lambda
        run: |
          npm run build
          zip -FSjr "dist/ingestion-lambda.zip" "dist/handler.js"

      - name: Build cleanup-lambda
        working-directory: cleanup-lambda
        run: |
          npm run build
          zip -FSjr "dist/cleanup-lambda.zip" "dist/handler.js"

      - name: Build email-filter-lambda
        working-directory: email-filter-lambda
        run: |
          npm run build
          zip -FSjr "dist/email-filter-lambda.zip" "dist/handler.js"

      - name: Build poller-lambdas
        working-directory: poller-lambdas
        run: |
          npm run build
          zip -FSjr "dist/poller-lambdas.zip" "dist/index.js"

      - name: Build fingerpost-queueing-lambda
        working-directory: fingerpost-queueing-lambda
        run: |
          npm run build
          zip -FSjr "dist/fingerpost-queueing-lambda.zip" "dist/handler.js"

      - name: Build Newswires app and UI
        working-directory: newswires
        run: |
          sbt clean scalafmtCheckAll compile test Debian/packageBin normalisePackageName

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: 'Editorial Tools::News Wires'
          configPath: cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out
            ingestion-lambda:
              - ingestion-lambda/dist/ingestion-lambda.zip
            cleanup-lambda:
              - cleanup-lambda/dist/cleanup-lambda.zip
            email-filter-lambda:
              - email-filter-lambda/dist/email-filter-lambda.zip
            poller-lambdas:
              - poller-lambdas/dist/poller-lambdas.zip
            fingerpost-queueing-lambda:
              - fingerpost-queueing-lambda/dist/fingerpost-queueing-lambda.zip
            newswires:
              - newswires/target/newswires.deb
