name: migrations checker
on:
  push

jobs:
  check-latest-migration:
    name: Check the latest migration version
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: eu-west-1
	        role-to-assume: ${{ secrets.SSM_AUTH }}
          
      - name: Checkout branch
        uses: actions/checkout@v5
      
      - name: Check the latest migration version
        run: 
          ./scripts/check-latest-migration.sh