name: Update Dependency Graph for sbt
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Java
        id: java
        uses: guardian/setup-scala@ac4ece07deb7cef715b8c975d4b8c77109c89ce8 # v1.1.3
      - name: Submit dependencies
        id: submit
        uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
        with:
          working-directory: newswires
      - name: Log snapshot for user validation
        id: validate
        run: cat ${{ steps.submit.outputs.snapshot-json-path }} | jq
    permissions:
      contents: write
